apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: app
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: denishsrijan/helloworld:b14.20230111.101621 # {"$imagepolicy": "flux-system:helloworld"}
