apiVersion: v1
kind: Service
metadata:
  name: helloworld-app-service
spec:
#  externalTrafficPolicy: Local
  type: LoadBalancer        # Exposes the service via the cloud provider's load balancer.
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
