---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: helloworld
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: b([0-9)+)\.(?P<ts>[0-9]+)\.(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: helloworld
  policy:
    numerical:
      order: asc

